# Generated by Django 4.0.6 on 2022-08-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tccs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcc',
            name='resumo',
            field=models.TextField(max_length=300),
        ),
    ]
